// Generated by CoffeeScript 1.6.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  if (!Cards) {
    throw "Hey, where are my Cards?";
  }

  if (!Lists) {
    throw "Look, I need those Lists, too!";
  }

  Cards.before.insert(function(userId, card) {
    var list;
    list = Lists.findOne(card.listId);
    if (__indexOf.call(list.memberIds, userId) >= 0 && !card.memberIds.length) {
      return card.memberIds.push(userId);
    }
  });

  Cards.before.update(function(userId, card, fieldNames, modifier, options) {
    var list, _ref, _ref1;
    if ((_ref = modifier.$set) != null ? _ref.listId : void 0) {
      list = Lists.findOne(modifier.$set.listId);
      if (__indexOf.call(list.memberIds, userId) >= 0 && !card.memberIds.length) {
        if (!((_ref1 = modifier.$addToSet) != null ? _ref1.memberIds : void 0)) {
          return modifier.$addToSet = {
            memberIds: userId
          };
        }
      }
    }
  });

}).call(this);

/*
//@ sourceMappingURL=plugin.map
*/
